---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapi-project
  labels:
    app: chat
data:
  default.conf: |
    upstream chat_project {
        server chat-service:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://chat_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }
