---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: chat-app
  labels:
    app: chat
spec:
  type: NodePort
  selector:
    app: chat-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
