---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-socket-server-deployment
  namespace: chat-app
  labels:
    app: chat

spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-socket-server
  template:
    metadata:
      labels:
        app: chat-socket-server
    spec:
      containers:
        - image: jsiona/chat-base:latest
          imagePullPolicy: Always
          name: chat-socket-server-container
          command: [
            "poetry", "run", "python", "socket_server.py",
          ]
          envFrom:
          - secretRef:
              name: chat-secret
          ports:
            - containerPort: 5000
              name: fastapi
          readinessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
