---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chat-app
  labels:
    app: chat
data:
  # Postgres
  POSTGRES_HOST: MC4wLjAuMA==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: anNpb25h
  POSTGRES_PASSWORD: QmVzdFBhc3N3b3JkRXZlcg==
  POSTGRES_DATABASE_NAME: Y2hhdC1hcHA=
